@startuml

class HBox
class VBOx
class BorderPane
class Canvas
class Button
class Label

class Sprite {
    - Image image
    - double x
    - double y
    - double width
    - double height
    - double rotation
    --
    + void render(GraphicsContext gc)
}

class AnimatedSprite {
    - Image[] frames
    --
    + void update(double deltaSeconds)
}

enum ViewKeys {
    MAIN_MENU_VIEW
    GAME_VIEW
    PAUSE_VIEW
    GAME_OVER_VIEW
    YOU_WON_VIEW
}

class ViewManager <<singleton>> {
    - StackPane root
    - BaseView currentView
    - Map<ViewKeys, BaseView> views
    --
    + void addView(BaseView view)
    + void removeView(ViewKeys key)
    + boolean hasKey(ViewKeys key)
    + Parent getRoot()
}

class ResourceManager <<singleton>> {
    - static ResourceManager instance
    - Map<String, Image> textures
    - Image missingTexture 
    --
    - ResourceManager()
    + static ResourceManager getInstance()
    + Image getTexture()
}

abstract class BaseView <<abstract>> {
    --
    + void onEnter()
    + void onExit()
}

class MainMenuView {
    - Button newGameButton
    - Button exitButton
    --
}
class PauseView {
    - Button resumeGameButton
    - Button mainMenuButton
    - Button exitButton
    --
}
class YouWonView {
    - Label score
    - Button playAgainButton
    - Button mainMenuButton
}
class GameOverView {
    - Label score
    - Button playAgainButton
    - Button mainMenuButton
}

class GameView {
    --
    + void renderGame(double deltaSeconds)
    - void renderBoard()
    - void renderEntity(Entity entity)
}

class Image
class GraphicsContext
class Affine
abstract Parent
class GameState

Parent <|-- BaseView
BaseView <|-- MainMenuView
BaseView <|-- PauseView
BaseView <|-- YouWonView
BaseView <|-- GameOverView
BaseView <|-- GameView
Sprite <|-- AnimatedSprite

ResourceManager <.. GameView : fetches textures
GraphicsContext <.. Sprite : renders on
ViewKeys <.. ViewManager : uses as keys

GameView "1" o-- "1" GameState : renders from
Sprite "1" o-- "1" Image : compose of
AnimatedSprite "1" o-- "many" Image : compose of
ViewManager "1" *-- "many" BaseView : manages views
ResourceManager "1" *-- "many" Image : compose of
GameView "1" *-- "many" Sprite : compose of
GameView "1" *-- "many" AnimatedSprite : compose of
GameView "1" *-- "1" Affine : compose of

GameView "1" *-- "1" Canvas : compose of
GameView "1" *-- "1" BorderPane : compose of
GameView "1" *-- "1" HBox : compose of
PauseView "1" *-- "1" VBOx : compose of
PauseView "1" *-- "3" Button : compose of
MainMenuView "1" *-- "1" VBox : compose of
MainMenuView "1" *-- "3" Button : compose of
YouWonView "1" *-- "1" VBox : compose of
YouWonView "1" *-- "2" Button : compose of
YouWonView "1" *-- "1" Label : compose of
GameOverView "1" *-- "1" VBox : compose of
GameOverView "1" *-- "2" Button : compose of
GameOverView "1" *-- "1" Label : compose of

@enduml

